server:
  name: app
  port: 8099
  env: dev

log:
  service: app
  level: info
  stdout: true
  dir: log
  extra_keys:
    - requestId

mysql:
  service: app
  addr: 172.17.0.2:3306
  user: root
  password: 123456
  database: demo
  charset: utf8mb4
  timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

redis:
  service: app
  addr: 172.17.0.3:6379
  password: 123456
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s


