CREATE TABLE `user`
(
    `id`            BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `company_id`    BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '公司id',
    `department_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '部门id',
    `name`          VARCHAR(255) NOT NULL DEFAULT '' COMMENT '姓名',
    `created_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at`    DATETIME              DEFAULT NULL COMMENT '删除时间',
    `created_by`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人id',
    `updated_by`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人id',
    `deleted_by`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除人id',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT = '人员表';
