definitions:
  gincontext.DtoRender:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  go-gin-web_apps_demo_internal_dto_dtoUser.UserCreateReq:
========
  go-gin-web_internal_apps_demoapp_dto_dtouser.UserCreateReq:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    properties:
      companyId:
        description: 公司id
        type: integer
      departmentId:
        description: 部门id
        type: integer
      name:
        description: 姓名
        type: string
    type: object
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  go-gin-web_apps_demo_internal_dto_dtoUser.UserCreateResp:
========
  go-gin-web_internal_apps_demoapp_dto_dtouser.UserCreateResp:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    properties:
      id:
        description: 数据自增id
        type: integer
    type: object
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  go-gin-web_apps_demo_internal_dto_dtoUser.UserDeleteReq:
========
  go-gin-web_internal_apps_demoapp_dto_dtouser.UserDeleteReq:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    properties:
      id:
        description: 数据自增id
        type: integer
    required:
    - id
    type: object
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  go-gin-web_apps_demo_internal_dto_dtoUser.UserDetailResp:
========
  go-gin-web_internal_apps_demoapp_dto_dtouser.UserDetailResp:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    properties:
      companyId:
        description: 公司id
        type: integer
      createdAt:
        description: 创建时间
        type: integer
      createdBy:
        description: 创建人id
        type: integer
      departmentId:
        description: 部门id
        type: integer
      id:
        description: 数据自增id
        type: integer
      name:
        description: 姓名
        type: string
      updatedAt:
        description: 更新时间
        type: integer
      updatedBy:
        description: 更新人id
        type: integer
    required:
    - id
    type: object
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  go-gin-web_apps_demo_internal_dto_dtoUser.UserPageListItem:
========
  go-gin-web_internal_apps_demoapp_dto_dtouser.UserPageListItem:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    properties:
      companyId:
        description: 公司id
        type: integer
      createdAt:
        description: 创建时间
        type: integer
      createdBy:
        description: 创建人id
        type: integer
      departmentId:
        description: 部门id
        type: integer
      id:
        description: 数据自增id
        type: integer
      name:
        description: 姓名
        type: string
      updatedAt:
        description: 更新时间
        type: integer
      updatedBy:
        description: 更新人id
        type: integer
    required:
    - id
    type: object
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  go-gin-web_apps_demo_internal_dto_dtoUser.UserPageListResp:
========
  go-gin-web_internal_apps_demoapp_dto_dtouser.UserPageListResp:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    properties:
      list:
        description: 数据列表
        items:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
          $ref: '#/definitions/go-gin-web_apps_demo_internal_dto_dtoUser.UserPageListItem'
========
          $ref: '#/definitions/go-gin-web_internal_apps_demoapp_dto_dtouser.UserPageListItem'
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
        type: array
      total:
        description: 数据总条数
        type: integer
    type: object
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  go-gin-web_apps_demo_internal_dto_dtoUser.UserUpdateReq:
========
  go-gin-web_internal_apps_demoapp_dto_dtouser.UserUpdateReq:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    properties:
      companyId:
        description: 公司id
        type: integer
      departmentId:
        description: 部门id
        type: integer
      id:
        description: 数据自增id
        type: integer
      name:
        description: 姓名
        type: string
    required:
    - id
    type: object
info:
  contact: {}
paths:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
  /demo/user/create:
========
  /demoapp/user/create:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建用户
        in: body
        name: req
        required: true
        schema:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
          $ref: '#/definitions/go-gin-web_apps_demo_internal_dto_dtoUser.UserCreateReq'
========
          $ref: '#/definitions/go-gin-web_internal_apps_demoapp_dto_dtouser.UserCreateReq'
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0,"data": "ok","msg": "success"}'
          schema:
            allOf:
            - $ref: '#/definitions/gincontext.DtoRender'
            - properties:
                data:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
                  $ref: '#/definitions/go-gin-web_apps_demo_internal_dto_dtoUser.UserCreateResp'
              type: object
      summary: 创建用户
      tags:
      - 用户管理
  /demo/user/delete:
========
                  $ref: '#/definitions/go-gin-web_internal_apps_demoapp_dto_dtouser.UserCreateResp'
              type: object
      summary: 创建用户
      tags:
      - 用户
  /demoapp/user/delete:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    post:
      consumes:
      - application/json
      parameters:
      - description: 删除用户
        in: body
        name: req
        required: true
        schema:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
          $ref: '#/definitions/go-gin-web_apps_demo_internal_dto_dtoUser.UserDeleteReq'
========
          $ref: '#/definitions/go-gin-web_internal_apps_demoapp_dto_dtouser.UserDeleteReq'
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0,"data": "ok","msg": "删除成功"}'
          schema:
            allOf:
            - $ref: '#/definitions/gincontext.DtoRender'
            - properties:
                data:
                  type: string
              type: object
      summary: 删除用户
      tags:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
      - 用户管理
  /demo/user/detail:
========
      - 用户
  /demoapp/user/detail:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    get:
      consumes:
      - application/json
      parameters:
      - description: 数据自增id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0,"data": "ok","msg": "success"}'
          schema:
            allOf:
            - $ref: '#/definitions/gincontext.DtoRender'
            - properties:
                data:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
                  $ref: '#/definitions/go-gin-web_apps_demo_internal_dto_dtoUser.UserDetailResp'
              type: object
      summary: 用户详情
      tags:
      - 用户管理
  /demo/user/pageList:
========
                  $ref: '#/definitions/go-gin-web_internal_apps_demoapp_dto_dtouser.UserDetailResp'
              type: object
      summary: 用户详情
      tags:
      - 用户
  /demoapp/user/pageList:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    get:
      consumes:
      - application/json
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数据条数
        in: query
        maximum: 1000
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0,"data": "ok","msg": "success"}'
          schema:
            allOf:
            - $ref: '#/definitions/gincontext.DtoRender'
            - properties:
                data:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
                  $ref: '#/definitions/go-gin-web_apps_demo_internal_dto_dtoUser.UserPageListResp'
              type: object
      summary: 用户列表分页
      tags:
      - 用户管理
  /demo/user/update:
========
                  $ref: '#/definitions/go-gin-web_internal_apps_demoapp_dto_dtouser.UserPageListResp'
              type: object
      summary: 用户列表分页
      tags:
      - 用户
  /demoapp/user/update:
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
    post:
      consumes:
      - application/json
      parameters:
      - description: 修改用户
        in: body
        name: req
        required: true
        schema:
<<<<<<<< HEAD:apps/demo/internal/docs/swagger.yaml
          $ref: '#/definitions/go-gin-web_apps_demo_internal_dto_dtoUser.UserUpdateReq'
========
          $ref: '#/definitions/go-gin-web_internal_apps_demoapp_dto_dtouser.UserUpdateReq'
>>>>>>>> develop:internal/apps/demoapp/docs/swagger.yaml
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0,"data": "ok","msg": "修改成功"}'
          schema:
            allOf:
            - $ref: '#/definitions/gincontext.DtoRender'
            - properties:
                data:
                  type: string
              type: object
      summary: 修改用户
      tags:
      - 用户
swagger: "2.0"
