server:
  name: go-gin-web
  port: 8099
  env: dev

log:
  service: go-gin-web
  level: info
  stdout: true
  dir: log
  extra_keys:
    - requestId

mysql:
  service: go-gin-web
  addr: 127.0.0.1:3306
  user: root
  password: 123456
  database: practice
  charset: utf8mb4
  timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

redis:
  service: go-gin-web
  addr: 127.0.0.1:6379
  password: 123456
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s


code_gen:
  module:
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-web
    description: 公司账户管理
    api_doc_tag: 公司账户管理
    api_group: companyAccount
    api_prefix: /go-gin-web/companyAccount
    package_name: companyAccount
    table_name: company_account
  model:
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-web
    description: 公司
    package_name: company
    table_name: company
  api:
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-web
    description: 禁用公司账户
    package_name: companyAccount
    sub_module_name: companyAccount
    target_filename: company_account.go
    http_method: POST
    function_name: Disable
    api_doc_tag: 公司账户管理
    api_group:  companyAccount
    api_prefix: /go-gin-web/companyAccount/
    api_suffix: disable


