mysql:
  service: genCode
  addr: 127.0.0.1:3306
  user: root
  password: 123456
  database: demo
  charset: utf8mb4
  timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

log:
  service: genCode
  level: info
  stdout: true
  dir: log
  extra_keys:
    - requestId

code_gen:
  mode: api
  service_name: app
  module:
    tpl_dir: internal/resource/codeTpl/module
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-web
    description: 平台应用
    api_doc_tag: 平台应用管理
    api_group: platform
    api_prefix: /app/platform
    package_name: platform
    table_name: platform
  model:
    tpl_dir: internal/resource/codeTpl/model
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-web
    description: 用户
    package_name: user
    table_name: user
  api:
    tpl_dir: internal/resource/codeTpl/api
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-web
    description: 禁用用户
    package_name: user
    sub_module_name: userAccount
    target_filename: user.go
    http_method: POST
    function_name: Disable
    api_doc_tag: 用户管理
    api_group: user
    api_prefix: /app/user/
    api_suffix: disable
    routerGroup: userGroup
