mysql_dsn: root:123456@tcp(127.0.0.1:3306)/practice?charset=utf8mb4&parseTime=True&loc=Local
layer_name_map:
  model: model
module:
  internal_app_root_dir: internal/demoapp
  project_root_dir: demoapp
  description: 公司账户管理
  api_doc_tag: 公司账户管理
  api_group: companyAccount
  api_prefix: /demoapp/companyAccount
  package_name: companyAccount
  table_name: company_account
model:
  internal_app_root_dir: internal/demoapp
  project_root_dir: demoapp
  description: 公司
  package_name: company
  table_name: company
api:
  internal_app_root_dir: internal/demoapp
  project_root_dir: demoapp
  description: 禁用公司账户
  package_name: companyAccount
  sub_module_name: companyAccount
  target_filename: company_account.go
  http_method: POST
  function_name: Disable
  api_doc_tag: 公司账户管理
  api_group:  companyAccount
  api_prefix: /demoapp/companyAccount/
  api_suffix: disable

